repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
#    -   id: check-shebang-scripts-are-executable
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
    -   id: autoflake
        args: ["--remove-unused-variables", "--expand-star-imports", "--remove-all-unused-imports"]
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
